import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className="h-lvh bg-background text-primary">
        {children}
        <Footer />
      </body>
    </html>
  );
}
