import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className="h-lvh flex flex-col justify-between py-24 px-[300px] bg-background text-primary">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
